<?php

function helsinki_config_colors() {
	return array(
		// 'brick' => array(
		// 	'primary' => array(
		// 		'color' => '#bd2719',
		// 		'light' => '#ffeeed',
		// 		'medium' => '#facbc8',
		// 		'dark' => '#800e04',
		// 	),
		// 	'secondary' => '',
		// 	'accent' => '',
		// ),
		'bus' => array(
			'primary' => array(
				'color' => '#0000bf',
				'light' => '#f0f0ff',
				'medium' => '#ccccff',
				'dark' => '#00005e',
				'content' => '#ffffff',
				'content-secondary' => '#1a1a1a',
			),
			'secondary' => '#fff0f7',
			'secondary-content' => '#1a1a1a',
			'accent' => '#00d7a7',
		),
		'coat-of-arms' => array(
			'primary' => array(
				'color' => '#0072c6',
				'light' => '#e6f4ff',
				'medium' => '#b5daf7',
				'dark' => '#005799',
				'content' => '#ffffff',
				'content-secondary' => '#1a1a1a',
			),
			'secondary' => '#e8f3fc',
			'secondary-content' => '#1a1a1a',
			'accent' => '#f5a3c7',
		),
		'copper' => array(
			'primary' => array(
				'color' => '#00d7a7',
				'light' => '#cffaf1',
				'medium' => '#9ef0de',
				'dark' => '#00a17d',
				'content' => '#1a1a1a',
				'content-secondary' => '#ffffff',
			),
			'secondary' => '#e8f3fc',
			'secondary-content' => '#1a1a1a',
			'accent' => '#f5a3c7',
		),
		'engel' => array(
			'primary' => array(
				'color' => '#ffe977',
				'light' => '#fff9db',
				'medium' => '#fff3b8',
				'dark' => '#dbc030',
				'content' => '#1a1a1a',
				'content-secondary' => '#ffffff',
			),
			'secondary' => '#f0f0ff',
			'secondary-content' => '#1a1a1a',
			'accent' => '#00d7a7',
		),
		'fog' => array(
		 	'primary' => array(
		 		'color' => '#9fc9eb',
		 		'light' => '#e8f3fc',
		 		'medium' => '#d0e6f7',
		 		'dark' => '#72a5cf',
				'content' => '#1a1a1a',
				'content-secondary' => '#ffffff',
			),
		 	'secondary' => '#e8f3fc',
			'secondary-content' => '#1a1a1a',
			'accent' => '#f5a3c7',
		),
		'gold' => array(
			'primary' => array(
				'color' => '#c2a251',
				'light' => '#f7f2e4',
				'medium' => '#e8d7a7',
				'dark' => '#9e823c',
				'content' => '#1a1a1a',
				'content-secondary' => '#ffffff',
			),
			'secondary' => '#e8f3fc',
			'secondary-content' => '#1a1a1a',
			'accent' => '#fd4f00',
		),
		'metro' => array(
			'primary' => array(
				'color' => '#fd4f00',
				'light' => '#ffeee6',
				'medium' => '#ffcab3',
				'dark' => '#bd2f00',
				'content' => '#1a1a1a',
				'content-secondary' => '#ffffff',
			),
			'secondary' => '#fff0f7',
			'secondary-content' => '#1a1a1a',
			'accent' => '#c2a251',
		),
		'silver' => array(
			'primary' => array(
				'color' => '#dedfe1',
				'light' => '#f7f7f8',
				'medium' => '#efeff0',
				'dark' => '#b0b8bf',
				'content' => '#1a1a1a',
				'content-secondary' => '#ffffff',
			),
			'secondary' => '#f0f0ff',
			'secondary-content' => '#1a1a1a',
			'accent' => '#c2a251',
		),
		'summer' => array(
			'primary' => array(
				'color' => '#ffc61e',
				'light' => '#fff4d4',
				'medium' => '#ffe49c',
				'dark' => '#cc9200',
				'content' => '#1a1a1a',
				'content-secondary' => '#ffffff',
			),
			'secondary' => '#fff9db',
			'secondary-content' => '#1a1a1a',
			'accent' => '#008741',
		),
		'suomenlinna' => array(
			'primary' => array(
				'color' => '#f5a3c7',
				'light' => '#fff0f7',
				'medium' => '#ffdbeb',
				'dark' => '#e673a5',
				'content' => '#1a1a1a',
				'content-secondary' => '#ffffff',
			),
			'secondary' => '#f0f0ff',
			'secondary-content' => '#1a1a1a',
			'accent' => '#0000bf',
		),
		'tram' => array(
			'primary' => array(
				'color' => '#008741',
				'light' => '#dff7eb',
				'medium' => '#a3e3c2',
				'dark' => '#006631',
				'content' => '#ffffff',
				'content-secondary' => '#1a1a1a',
			),
			'secondary' => '#fff9db',
			'secondary-content' => '#1a1a1a',
			'accent' => '#ffc61e',
		),
	);
}
